### ISSUE TITLE
在使用其他数据集训练时出现无法保存模型的错误。

### ISSUE THREAD

**Issue by Fritzyuan** [CASIA-IVA-Lab/AnomalyGPT#67]
作者你好，我在使用AnomalyGPT进行其他数据集训练时出现了这样的错误，无法保存训练的model.pt文件：
Traceback (most recent call last): 
File "/workspace/AnomalyGPT/code/train_mvtec.py", line 115, in main(**args) 
File "/workspace/AnomalyGPT/code/train_mvtec.py", line 109, in main agent.save_model(args['save_path'], 0) 
File "/workspace/AnomalyGPT/code/model/agent.py", line 75, in save_model torch.save(checkpoint, f'{path}/pytorch_model.pt') 
File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 441, in save _save(obj, opened_zipfile, pickle_module, pickle_protocol) 
File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 653, in _save pickler.dump(obj) 
TypeError: cannot pickle 'torch._C._distributed_c10d.ProcessGroup' object

其中对./code/datasets/mvtec.py的修改在：
![image](https://github.com/CASIA-IVA-Lab/AnomalyGPT/assets/132838629/fdf128d1-7e59-4e3b-9a68-124292827789)
![image](https://github.com/CASIA-IVA-Lab/AnomalyGPT/assets/132838629/18bb613e-52c7-4351-b35c-7b6a28cd75f7)

训练用到的数据集的格式是和MVTec数据集一致的。想请教一下这个TypeError该如何解决？

**Comment by Grace-yafei** [comment]
您好，看到您关闭了问题，请问是怎么解决的

**Comment by Fritzyuan** [comment]
> 您好，看到您关闭了问题，请问是怎么解决的

使用requirement中对应版本的Pytorch。 使用2.0以上的pytorch会出现这个问题

**Comment by F-Yuan303** [comment]
您好，可以请问一下您使用的数据集是什么吗？非常感谢
